// Absolute imports
import React, { Fragment } from "react";
import { BrowserRouter as Router, Route } from "react-router-dom";
import { v1 as uuidv1 } from "uuid";

// Relative imports
import AppBar from "./core/components/AppBar";
import NavigationDrawer from "./core/components/NavigationDrawer";
import About from "./about/About";
import Notes from "./notes/Notes";
import NoteService from "./notes/services/NoteService";

/**
 * Class Component App.
 * Stateful & Lifecycle-hooks.
 * @returns the App React element.
 */
class App extends React.Component {
  // state holds information about the component to initialise, change, and use on it’s own.
  state = {
    notes: [],
    isLoading: false,
    isMenuOpen: false,
    reloadHasError: false,
    saveHasError: false,
  };

  /**
   * Lifecycle method that catch JavaScript errors during render, log those errors, and display a fallback UI instead of the component tree that crashed.
   * @param {*} error the actual error thrown.
   * @param {*} errorInfo an object with a componentStack property containing the component stack trace information.
   */
  componentDidCatch(error, errorInfo) {
    console.error(error, errorInfo);
    this.setState({ reloadHasError: true });
  }

  /**
   * Lifecycle method that only execute on the first rendering.
   */
  componentDidMount() {
    this.handleReload();
  }

  /**
   * Creates a new note with the text informed.
   * @param {string} text of the note
   */
  handleAddNote = (text) => {
    this.setState((prevState) => {
      const notes = prevState.notes.concat({ id: uuidv1(), text });

      this.handleSave(notes);

      return { notes };
    });
  };

  /**
   * Moves the note up or down in the array.
   * @param {string} direction up or down.
   * @param {number} index / position in the array.
   */
  handleMove = (direction, index) => {
    this.setState((prevState) => {
      const newNotes = prevState.notes.slice();
      const removedNote = newNotes.splice(index, 1)[0];

      if (direction === "up") {
        newNotes.splice(index - 1, 0, removedNote);
      } else {
        newNotes.splice(index + 1, 0, removedNote);
      }

      this.handleSave(newNotes);

      return {
        notes: newNotes,
      };
    });
  };

  /**
   * Delete the note from the array.
   * @param {string} id note's unique identifier generated by uuidv1().
   */
  handleDelete = (id) => {
    this.setState((prevState) => {
      const newNotes = prevState.notes.slice();
      const index = newNotes.findIndex((note) => note.id === id);
      newNotes.splice(index, 1);

      this.handleSave(newNotes);

      return {
        notes: newNotes,
      };
    });
  };

  /**
   * Edit note's currently text
   * @param {string} id note's unique identifier generated by uuidv1().
   * @param {string} text note's new text
   */
  handleEdit = (id, text) => {
    this.setState((prevState) => {
      const newNotes = prevState.notes.slice();
      const index = newNotes.findIndex((note) => note.id === id);
      newNotes[index].text = text;

      this.handleSave(newNotes);

      return {
        notes: newNotes,
      };
    });
  };

  /**
   * Calls NoteService to retrieve the notes from localStorage
   */
  handleReload = () => {
    this.setState({ isLoading: true, reloadHasError: false });
    NoteService.load()
      .then((notes) => {
        this.setState({ notes, isLoading: false });
      })
      .catch(() => {
        this.setState({ isLoading: false, reloadHasError: true });
      });
  };

  /**
   * Calls NoteService to save the notes on localStorage
   * @param {Array<Note object>} notes
   */
  handleSave = (notes) => {
    this.setState({ isLoading: true, saveHasError: false });
    NoteService.save(notes)
      .then(() => {
        this.setState({ isLoading: false });
      })
      .catch(() => {
        this.setState({ isLoading: false, saveHasError: true });
      });
  };

  handleOpenMenu = () => {
    this.setState({ isMenuOpen: true });
  };

  handleCloseMenu = () => {
    this.setState({ isMenuOpen: false });
  };

  render() {
    const {
      notes,
      isLoading,
      isMenuOpen,
      reloadHasError,
      saveHasError,
    } = this.state;

    return (
      <Router>
        <div>
          <AppBar
            isLoading={isLoading}
            saveHasError={saveHasError}
            onSaveRetry={() => {
              this.handleSave(notes);
            }}
            onOpenMenu={this.handleOpenMenu}
          />
          <div className="container">
            <React.Fragment>
              <Route
                path="/"
                exact
                render={(props) => (
                  <Notes
                    notes={notes}
                    reloadHasError={reloadHasError}
                    onRetry={this.handleReload}
                    onAddNote={this.handleAddNote}
                    onMove={this.handleMove}
                    onDelete={this.handleDelete}
                    onEdit={this.handleEdit}
                  />
                )}
              />
              <Route path="/about" component={About} />
            </React.Fragment>
          </div>
          <NavigationDrawer
            isOpen={isMenuOpen}
            onCloseMenu={this.handleCloseMenu}
          />
        </div>
      </Router>
    );
  }
}

export default App;
